### PR TITLE
optimize sensor class

### PR DESCRIPTION
**Pull request by SchumyHao**
save model info in all sensor class.
Add className in sensor class, use className for channel ID.

Signed-off-by: SchumyHao <schumyhaojl@126.com>

### CODE REVIEW

**Comment by SchumyHao** [comment]
In my home.
There are some optimize point.
1. All device icon are correct.
2. 86plug can be controlled.
3. lock device appeared.

model info is useful for me to make this adapter support protocol 2.0.x.

**Comment by SchumyHao** [comment]
fix

**Comment by SchumyHao** [comment]
Link issue I have created #80

**Comment by SchumyHao** [comment]
Any update about this PR? @GermanBluefox @Apollon77 
Thanks very much. If I have distrubed you, please let me know.
If you have any comment, tell me and I'll try to fix it.

**Comment by Apollon77** [comment]
I will try to find some time later today to have a rough look, but because I do not have such devices and if you tested it best possible, I'm fine

**Comment by SchumyHao** [comment]
Device control is OK.
Because this will only change 86plug control command. I tested with my devices.
This [link](https://docs.google.com/spreadsheets/d/1O7ZW8EgJecnw0eZ2siUmD-UFUU0pxYkdikrOpNX1wTA/edit#gid=0&range=F12) shows the write command 86plug should be from protocol [1.0.9](https://github.com/aqara/aiot-gateway-local-api)

Report and heartbeat command will not use sensor.type value.

I think you can review this patch from those aspects

1. Device Channel ID is not changed, Make sure this is compatiable with old version.
2. Is there any code may cause adapter crash?

**Comment by SchumyHao** [comment]
Hi @Apollon77 
Any update? Thanks~

**Comment by Apollon77** [comment]
lost from radar ... tonight!

**Comment by SchumyHao** [comment]
So much thanks @Apollon77

**Comment by Apollon77** [comment]
Today ... i promise :-(

**Comment by Apollon77** [comment]
Code wise it seems to be ok, I would approve and merge it and also let it test by users as new latest version

**Comment by SchumyHao** [comment]
@Apollon77  Thanks.
With this patch, I can goon add protocol 2.0.x support.

**Comment by Apollon77** [comment]
Then happy merging :-)

**Pull request merged**
