### PR TITLE
Add acpartner.v3 support. Add 2.0.x protocol support

### PR DESCRIPTION
**Pull request by SchumyHao**
Signed-off-by: SchumyHao <schumyhaojl@126.com>

### CODE REVIEW

**Comment by SchumyHao** [comment]
```
States 127.0.0.1:49910 Redis error: Error: read ECONNRESET
```

Not sure why only node 6 has issue.

**Comment by Apollon77** [comment]
I will check it. Else we simply remove node6 from testing. It is eol and js-Controller 2.0 is no longer supporting it

**Comment by Apollon77** [comment]
Not in fact the redis-error is not nodejs6 specific and happens in all versions but is no real problem. This will disapear as soon as I clean up logging in the js-controller master hopefully today :-)

When you check deeper then you see that in nodejs 6 somehow/whyever the ".illumination" dstate does not get created ... question is why ...

**Comment by SchumyHao** [comment]
> I will check it. Else we simply remove node6 from testing. It is eol and js-Controller 2.0 is no longer supporting it

Without my patches, same error message print for node6.

[log](https://travis-ci.org/smarthomefans/ioBroker.mihome/builds/530677048) can be got here

**Pull request merged**
